### PR TITLE
Fix/issue 66

### LINKED ISSUE #66: Enabled event listener mutates cornerstone events listener list
I'm getting errors when passing in `onElementEnabled` to the viewport. Because i changed the code to handle all events in #60  this bug has surfaced. 

This is caused when iterating over the listener list in [cornestone events](https://github.com/cornerstonejs/cornerstone/blob/c29c4fa3c1a5fd3e611de953c9f1c90de4a7aafe/src/events.js#L99-L101). In my case the initial length of the listener is 3, but when the enabled event code fires it removes its listener and the list becomes length 2. So when `i=3` `stack[i]` becomes `undefined` and we get:

```console
Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
```

Is there a reason for removing the listener at this point or could this be handled in the unmount like other events? Additionally should the changes from #60 exclude the events which the viewport exposes functions for or should it remain as is?

https://github.com/cornerstonejs/react-cornerstone-viewport/blob/6d829fcccfbffcbb7a40f112b110e68389a9f554/src/CornerstoneViewport/CornerstoneViewport.js#L548-L570

### PR DESCRIPTION
**Pull request by dannyrb**
fixes #66

### CODE REVIEW

File: src/CornerstoneViewport/CornerstoneViewport.js [hunk 1]
```diff
@@ -554,28 +566,31 @@ class CornerstoneViewport extends Component {
...
+    if (this.props.onElementEnabled && !clear) {
       cornerstone.events.addEventListener(
         cornerstone.EVENTS.ELEMENT_ENABLED,
         handler
       );
     }
+
+    // Stop Listening
+    if (clear) {
+      // Stop Listening
```
Comment (dannyrb) [inline src/CornerstoneViewport/CornerstoneViewport.js]:
```suggestion
```

**Comment by dannyrb** [comment]
The escape-hatch demo was previously broken, but appears to work as expected. Other example pages also working:

https://deploy-preview-69--react-cornerstone-viewport.netlify.com/escape-hatch
